import 'package:ecommerce/models/product.dart';


class MyProducts {
  static List<Product> allProducts = [
    Product(
        id: 1,
        name: 'White Sneaker',
        category: 'Trending Now',
        image: 'assets/sneakers/classic-sneakers-for-men-under.jpg',
        description: 'Classic Sneaker for men',
        price: 200,
        quantity: 1),
    Product(
        id: 2,
        name: 'White Sneaker',
        category: 'Trending Now',
        image: 'assets/sneakers/sneaker2.jpeg',
        description: 'Classic Sneaker for men',
        price: 300,
        quantity: 1),
    Product(
        id: 3,
        name: 'Black Sneaker',
        category: 'Trending Now',
        image: 'assets/sneakers/sneaker3.jpeg',
        description: 'Classic Sneaker for men',
        price: 300,
        quantity: 1),
    Product(
        id: 4,
        name: 'White Sneaker',
        category: 'Trending Now',
        image: 'assets/sneakers/sneaker4.jpeg',
        description: 'Classic Sneaker for men',
        price: 300,
        quantity: 1),
    Product(
        id: 5,
        name: 'White Sneaker',
        category: 'Trending Now',
        image: 'assets/sneakers/sneaker5.jpeg',
        description: 'Classic Sneaker for men',
        price: 300,
        quantity: 1),
    Product(
        id: 6,
        name: 'White Sneaker',
        category: 'Trending Now',
        image: 'assets/sneakers/sneaker6.jpeg',
        description: 'Classic Sneaker for men',
        price: 300,
        quantity: 1),
    Product(
        id: 1,
        name: 'black jacket',
        category: 'Trending Now',
        image: 'assets/jackets/jacket1.jpeg',
        description: 'Woman\'s black jacket',
        price: 500,
        quantity: 1),
    Product(
        id: 1,
        name: 'black jacket',
        category: 'Trending Now',
        image: 'assets/jackets/jacket2.jpeg',
        description: 'Man\'s black jacket',
        price: 600,
        quantity: 1),
    Product(
        id: 1,
        name: 'black jacket',
        category: 'Trending Now',
        image: 'assets/jackets/jacket3.jpeg',
        description: 'Man\'s black jacket',
        price: 400,
        quantity: 1),
    Product(
        id: 1,
        name: 'black jacket',
        category: 'Trending Now',
        image: 'assets/jackets/jacket4.jpeg',
        description: 'Man\'s black jacket',
        price: 400,
        quantity: 1),
    Product(
        id: 1,
        name: 'white jacket',
        category: 'Trending Now',
        image: 'assets/jackets/jacket5.jpeg',
        description: 'Man\'s black jacket',
        price: 300,
        quantity: 1),
    Product(
        id: 1,
        name: 'blue jacket',
        category: 'Trending Now',
        image: 'assets/jackets/jacket6.jpeg',
        description: 'jeans jacket',
        price: 500,
        quantity: 1),
  ];
  static List<Product> sneakersList = [
    Product(
        id: 1,
        name: 'White Sneaker',
        category: 'Trending Now',
        image: 'assets/sneakers/classic-sneakers-for-men-under.jpg',
        description: 'Classic Sneaker for men',
        price: 200,
        quantity: 1),
    Product(
        id: 2,
        name: 'White Sneaker',
        category: 'Trending Now',
        image: 'assets/sneakers/sneaker2.jpeg',
        description: 'Classic Sneaker for men',
        price: 300,
        quantity: 1),
    Product(
        id: 3,
        name: 'Black Sneaker',
        category: 'Trending Now',
        image: 'assets/sneakers/sneaker3.jpeg',
        description: 'Classic Sneaker for men',
        price: 300,
        quantity: 1),
    Product(
        id: 4,
        name: 'White Sneaker',
        category: 'Trending Now',
        image: 'assets/sneakers/sneaker4.jpeg',
        description: 'Classic Sneaker for men',
        price: 300,
        quantity: 1),
    Product(
        id: 5,
        name: 'White Sneaker',
        category: 'Trending Now',
        image: 'assets/sneakers/sneaker5.jpeg',
        description: 'Classic Sneaker for men',
        price: 300,
        quantity: 1),
    Product(
        id: 6,
        name: 'White Sneaker',
        category: 'Trending Now',
        image: 'assets/sneakers/sneaker6.jpeg',
        description: 'Classic Sneaker for men',
        price: 300,
        quantity: 1),
  ];
  static List<Product> jacketList = [
    Product(
        id: 1,
        name: 'black jacket',
        category: 'Trending Now',
        image: 'assets/jackets/jacket1.jpeg',
        description: 'Woman\'s black jacket',
        price: 500,
        quantity: 1),
    Product(
        id: 1,
        name: 'black jacket',
        category: 'Trending Now',
        image: 'assets/jackets/jacket2.jpeg',
        description: 'Man\'s black jacket',
        price: 600,
        quantity: 1),
    Product(
        id: 1,
        name: 'black jacket',
        category: 'Trending Now',
        image: 'assets/jackets/jacket3.jpeg',
        description: 'Man\'s black jacket',
        price: 400,
        quantity: 1),
    Product(
        id: 1,
        name: 'black jacket',
        category: 'Trending Now',
        image: 'assets/jackets/jacket4.jpeg',
        description: 'Man\'s black jacket',
        price: 400,
        quantity: 1),
    Product(
        id: 1,
        name: 'white jacket',
        category: 'Trending Now',
        image: 'assets/jackets/jacket5.jpeg',
        description: 'Man\'s black jacket',
        price: 300,
        quantity: 1),
    Product(
        id: 1,
        name: 'blue jacket',
        category: 'Trending Now',
        image: 'assets/jackets/jacket6.jpeg',
        description: 'jeans jacket',
        price: 500,
        quantity: 1),
  ];
}
